import { useState } from 'react';
import DataBadge from '../DataBadge';
import { generateProcurementPlan } from '../../lib/recommendations';
import './ProcurementOrchestrator.css';

export default function ProcurementOrchestrator({ scenarioResult, onViewRoutes }) {
  const [compareOpen, setCompareOpen] = useState(false);
  const [expandedWhy, setExpandedWhy] = useState(null);

  const plan = generateProcurementPlan({ hormuzDisruptionPct: scenarioResult?.hormuzDisruptionPct ?? 0 });

  function downloadPlan() {
    const lines = [
      'AI PROCUREMENT RECOMMENDATION — DECISION-SUPPORT DRAFT (not an executed order)',
      `Scenario: ${scenarioResult?.scenario?.label ?? 'n/a'} @ severity ${scenarioResult?.severityPct ?? 0}%`,
      `Modelled supply gap: ${scenarioResult?.supplyGapPct ?? 0}% · Modelled price impact: ${scenarioResult?.priceImpactPct ?? 0}%`,
      '',
      ...plan.flatMap((p) => [
        `PRIORITY ${p.priority}: ${p.supplier} (${p.route})`,
        `  Risk: ${p.risk}  |  Cost impact: ${p.costImpact}  |  Availability: ${p.availability}  |  Confidence: ${p.confidence}/100`,
        `  Action: ${p.reason}`,
        `  Why: ${p.whyReasons.join(' ')}`,
        '',
      ]),
      'Generated by a decision-support prototype. This is a draft recommendation for a human procurement team to review — no orders have been placed and no suppliers have been contacted.',
    ];
    const blob = new Blob([lines.join('\n')], { type: 'text/plain' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'procurement-plan-draft.txt';
    a.click();
    URL.revokeObjectURL(url);
  }

  return (
    <div className="orchestrator">
      <p className="orchestrator__flag">
        <DataBadge type="AI_INSIGHT" /> Decision-support draft — no orders placed, no suppliers contacted
      </p>

      <div className="orchestrator__cards">
        {plan.map((p) => (
          <div key={p.priority} className="rec-card2">
            <div className="rec-card2__head">
              <span className="rec-card2__priority">Priority {p.priority}</span>
              <span className="rec-card2__confidence mono">{p.confidence}/100 confidence</span>
            </div>
            <h4 className="rec-card2__supplier">{p.supplier}</h4>
            <p className="rec-card2__route">{p.route}</p>
            <dl className="rec-card2__grid">
              <div><dt>Risk</dt><dd>{p.risk}</dd></div>
              <div><dt>Cost impact</dt><dd>{p.costImpact}</dd></div>
              <div><dt>Availability</dt><dd>{p.availability}</dd></div>
            </dl>
            <p className="rec-card2__reason">{p.reason}</p>
            <button
              className="rec-card2__why-toggle"
              onClick={() => setExpandedWhy(expandedWhy === p.priority ? null : p.priority)}
            >
              WHY THIS RECOMMENDATION? {expandedWhy === p.priority ? '−' : '+'}
            </button>
            {expandedWhy === p.priority && (
              <ul className="rec-card2__why-list">
                {p.whyReasons.map((r) => <li key={r}>{r}</li>)}
              </ul>
            )}
            <button className="btn-small" onClick={() => onViewRoutes?.(p.supplierId || p.supplier)}>
              View on risk map →
            </button>
          </div>
        ))}
      </div>

      <div className="orchestrator__actions">
        <button className="btn btn--ghost btn--compact" onClick={() => setCompareOpen((o) => !o)}>
          {compareOpen ? 'Hide comparison' : 'Compare suppliers'}
        </button>
        <button className="btn btn--primary btn--compact" onClick={downloadPlan}>
          Generate procurement plan (.txt)
        </button>
      </div>

      {compareOpen && (
        <div className="compare-table">
          <div className="compare-table__row compare-table__row--head">
            <span>Supplier</span><span>Risk</span><span>Cost impact</span><span>Availability</span><span>Confidence</span>
          </div>
          {plan.map((p) => (
            <div key={p.priority} className="compare-table__row">
              <span>{p.supplier}</span><span>{p.risk}</span><span>{p.costImpact}</span><span>{p.availability}</span><span>{p.confidence}/100</span>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
